### ISSUE TITLE
Account line type summary view.

### ISSUE THREAD

**Issue by vincentdavis** [Colorado-Realestate-Data/CO-Database#15]
A basic view and/or rest api to get the following data.
total (sum) of values by:
property by tax_year by tax_type.

The function might be something like this, but using sql not for loops.

```python
# sudo code
tax_type_summary_by_year(parcel_id, tax_year, tax_type=all):
    select account rows where parcel_id== parcel_id and tax_year=tax_year
    for each tax_type, sum all entries
        return tax_type_sum
```

**Comment by pprolancer** [comment]
add new endpoint: /api/v1/account/tax_type_summary
we can use query parameters to filter by: tax_year, min_tax_year, max_tax_year and property__parid

examples: 
/api/v1/account/tax_type_summary?tax_year=2015
/api/v1/account/tax_type_summary?min_tax_year=2013
/api/v1/account/tax_type_summary?max_tax_year=2016
/api/v1/account/tax_type_summary?property_parid=M035100
